
version: 2

models:
    - name: my_third_dbt_model
      description: "A starter dbt model"
      columns:
          - name: sum
            description: "The sum of the id column in the my_second_dbt_model table"